### PR TITLE
create settings ini file if not exists

### PR DESCRIPTION
**Pull request by Vodacek**

### CODE REVIEW

**Comment by ZaneDubya** [comment]
@Vodacek Is this required? I believe WritePrivateProfileString creates the file if it does not exist.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya If ini file does not exist, it's created automatically when you first saving value into it. For example, when you hit login button at login screen. (if not changed in c6819ff).

So, not sure if we actually need create file this way, but its not going break anything.

**Comment by Vodacek** [comment]
I try that and I have to create that file manually.

---

**Comment by Vodacek** [comment]
No file is not created on save, see SettingVars.cs line 38. 

---

**Comment by ZaneDubya** [comment]
@Vodacek That is weird. Per MSDN (referring to WritePrivateProfileString):

> If lpFileName contains a full path and file name and the file does not exist, WritePrivateProfileString creates the file. The specified directory must already exist.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms725501(v=vs.85).aspx

**Comment by PatrikSamuelTauchim** [comment]
@Vodacek then, we need this. But it was working before c6819ff, because IniFile handles file creation when needed.

@ZaneDubya  I guess, is because of you condition "if (m_IniFile != null)" at line 38 in SettingVars, as @Vodacek stated. If there is no ini file, we are not even trying to write. And if we are not writing, we are not creating any file. :-)

**Comment by Vodacek** [comment]
I am running at Windows 8.1 and thats it why using system calls for any trivial task is not good choise in my opinion. 

---

**Comment by ZaneDubya** [comment]
Ok. Merging.

**Pull request merged**
