### PR TITLE
ColorPickers rework

### PR DESCRIPTION
**Pull request by PatrikSamuelTauchim**
- new ColorPickerBox - Checkbox filled with color serves as fancy
  ColorPicker
- ColorPickers replaced by ColorPickerBoxes
- values from ColorPickerBoxes and CheckBoxes for Speech and Messaging
  are now saved/loaded

### CODE REVIEW

**Comment by ZaneDubya** [comment]
@Eskymak Awesome! Will look at this as soon as I get home.

**Comment by ZaneDubya** [comment]
@Eskymak this looks really good. I'm going to merge it. One thing to keep on your radar - I see a lot of duplicated code between ColorPicker and ColorPickerBox. If you have the time, could you see if you could make CPB inherit from CP?

**Comment by ZaneDubya** [comment]
@Eskymak I like how you repurposed the checkbox gump graphic. :)

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Thanks! Yeah, I did just copy of original ColorPicker, renamed class, used few lines of code from CheckBox to draw that box and placed that color rectangle in the middle. :-)

This code needs more things to fix in future, but now I am happy it works... I had to rename "m_Inactive" to something else :D

**Pull request merged**
