### PR TITLE
partial hue for items and statics

### PR DESCRIPTION
**Pull request by Vodacek**

### CODE REVIEW

**Comment by ZaneDubya** [comment]
Looks good. Thanks!

**Comment by SaschaKP** [comment]
Just a question, is partialhue working on your side? I can't see partial hued items as "partial", since they get totally hued.

**Comment by SaschaKP** [comment]
Ok, found it, vertex are generated only in ground items, not in mobile (world animations and such) and equipment in general, may I ask you, ZaneDubya, were I can find were the content of paperdoll and backpacks in general are drawn? I've already found were to place the correct vertex options in world animations, but I'm missing the rest of the cases...

**Comment by ZaneDubya** [comment]
Hey @uoitalia - vertexes for UI items are generated in [ItemGumpling](https://github.com/ZaneDubya/UltimaXNA/blob/master/dev/Ultima/UI/Controls/ItemGumpling.cs#L105). The paper doll vertexes are generated in [ItemGumplingPaperdoll](https://github.com/ZaneDubya/UltimaXNA/blob/master/dev/Ultima/UI/Controls/ItemGumplingPaperdoll.cs#L56). Let me know if this does not answer your question.

**Pull request merged**
