### PR TITLE
Options-macro menu dialog design work

### PR DESCRIPTION
**Pull request by robertdeclaux**
Basic design of macro dialog

### CODE REVIEW

**Comment by ZaneDubya** [comment]
@robertdeclaux Sorry for waiting on this one - I thought it would be much harder to merge. It wasn't ;).

Looks good, merging.

**Comment by robertdeclaux** [comment]
I wish it was complete sorry for disappointment.

**Comment by ZaneDubya** [comment]
Haha, I'm not disappointed! Maybe someday, someone will take on macros ;)

**Comment by ZaneDubya** [comment]
At least now they have an interface for them!

**Pull request merged**
