### PR TITLE
Journal feature

### PR DESCRIPTION
**Pull request by robertdeclaux**
Journal feature

### CODE REVIEW

**Comment by PatrikSamuelTauchim** [comment]
Just did quick test.
When I say something, the scrollbar slider is moved under actual scrollbar (under or on top of bottom arrow). And is really hard to move it up then. If you say even more, it falls out of journal completely

**Comment by PatrikSamuelTauchim** [comment]
If I resizing Journal (making it smaller) slider also runs away, in opposite direction :-)

Feature request: Save journal size and maybe possition to Settings :-)
Otherwise is nice, I was really missing this piece of UO UI

**Comment by ZaneDubya** [comment]
Thank you @robertdeclaux!

With regards to the escaping slider bug - I think this may be an issue with the underlying scrollbar class. I'll see if I can fix the problem there.

**Comment by robertdeclaux** [comment]
I confirm too but the i used skills gump as a template (scroll bar is the same one used on skills gump). I'm not much wise about the ScrollBar.cs, may be Zane can handle it.

**Pull request merged**
