### PR TITLE
Screen resolution dïalog

### PR DESCRIPTION
**Pull request by PatrikSamuelTauchim**
Added screen resolution dialog before engine starts

### CODE REVIEW

**Comment by PatrikSamuelTauchim** [comment]
Uh, sorry wrong way!

**Comment by PatrikSamuelTauchim** [comment]
Thanks for valuable reply and interesting thoughts. Since I am not not so familiar with programming, I just implemented features that were missing for me. But I will definitely try to go more in deep and look at gumps, because that is the right way ofcourse.

**Comment by ZaneDubya** [comment]
@Eskymak, would you like to continue working on this feature? I don't have any plans to add it myself, but I think it would be a good feature to add, so I wanted to re-open it as an issue to work on in the future.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya, I had no time to look into gumps until now. Are you using some editor for creating gumps layout? Or it is Gump Studio compatible format?

**Comment by ZaneDubya** [comment]
@Eskymak No, the gumps are created with code; there is no editor. It's not ideal. An example of a client-side gump is:

https://github.com/ZaneDubya/UltimaXNA/blob/master/dev/UltimaGUI/LoginGumps/CreateCharAppearanceGump.cs

One could certainly make the case for adding GumpStudio support, but I'm not personally aware of how that program works or what the output format is. I believe GumpStudio creates interfaces for RunUO; if that is the case, the client doubtless does not have support for what the output of that program would be.

**Pull request closed without merging**
