### PR TITLE
Double Clicking on Health Bars

### PR DESCRIPTION
**Pull request by PatrikSamuelTauchim**
Double Clicking on Health Bars of Other Players Does now Bring up Their Paper Dolls
 #416

### CODE REVIEW

**Comment by fdsprod** [comment]
Just a heads up,  We needs a message box check if the health bar is double clicked in war mode and the player being attacked is not a criminal or a murderer.  To add to this, we should add a setting to allow the player to turn off this query.

**Comment by fdsprod** [comment]
http://www.mortalonline.com/forums/attachments/uo_flag-jpg.6697

Image for reference.

**Comment by PatrikSamuelTauchim** [comment]
Can someone implement function to check if Mobile isCriminal/isMurderer/isWhatever?

**Comment by fdsprod** [comment]
I believe Mobile has a property Notoriety.  It is a flag (we should probably make an enum for) for the following values

```
    /// 0x1: Innocent (Blue)
    /// 0x2: Friend (Green)
    /// 0x3: Grey (Grey - Non Criminal)
    /// 0x4: Criminal (Grey)
    /// 0x5: Enemy (Orange)
    /// 0x6: Murderer (Red)
    /// 0x7: Invulnerable (Yellow)
```

See https://github.com/ZaneDubya/UltimaXNA/blob/67d33dad0bcb88d47a8874217c93df6eabe9fbad/dev/Ultima/Network/Server/MobileIncomingPacket.cs

**Comment by PatrikSamuelTauchim** [comment]
For now, I utilized existing MsgBox for CrimeQuery and hardcoded notoriety values.
It seems like this code needs to be placed somewhere else anyway,in order to be shared by onInteractButton from WorldInput and Background_MouseDoubleClickEvent on health bars.

I noticed that openning of paperdoll is already handled by World.Interaction.DoubleClick(Mobile); so I reworked code. However this always opens paperdoll, even if we are in warmode (we dont want open it in warmode). I cannot find code to change this.

I also noticed that it also sends DoubleClickPacket I am not sure, if we also need that while sending AttackRequestPacket.
Can someone clarify? :-)

**Comment by PatrikSamuelTauchim** [comment]
CrimeQuery (if enabled) is now showing while attacking by DoubleClick in game and also by DoubleClick on healtbar. And code is shared.

**Comment by PatrikSamuelTauchim** [comment]
crimequeryjpg

**Comment by ZaneDubya** [comment]
Ready to merge?

[edit] I mean ready for me to test - will anything more be added to this patch? Thank you!

**Comment by PatrikSamuelTauchim** [comment]
Well, I think it is ready for test. Especially for comparing with classic client.

**Comment by ZaneDubya** [comment]
Looks good!

**Pull request merged**
