### PR TITLE
System: PartySystem Added

### PR DESCRIPTION
**Pull request by msx752**
i created myself PartySystem for ultimaXNA. 
it is working but it has three bugs/development necessary here:https://github.com/ZaneDubya/UltimaXNA/issues/330

Please look at the system :) Thank You.

extra conflicts (not necessary for PartySystem):
dev/Ultima/UI/Controls/TextEntry.cs
dev/Ultima/Data/ClientVersion.cs (my client.exe dont have fileversion)
dev/Core/UI/AControl.cs

### CODE REVIEW

**Comment by ZaneDubya** [comment]
@MSAlih1 This is awesome - thank you! I need to take a deep look at it - but based on a quick look it should take less time to integrate with the main branch!

**Comment by ZaneDubya** [comment]
This is quite good!

**Comment by msx752** [comment]
infinite in queue :)

**Comment by ZaneDubya** [comment]
Haha, sorry! I am working on it! But it's a big add (you added a ton of functionality!) and making sure that it gets properly integrated isn't easy! I'll try to have it in this weekend.

**Comment by ZaneDubya** [comment]
@msx752 I'm leaving some comments where I'd like to get your feedback. This is my first time using the code review function, so if the comments look a little wonky, now you know why ;0

**Comment by msx752** [comment]
okey 👍  now i see but
@ZaneDubya WorldClient.cs line:1130
they are static message for other party members when someone get paralized or party leader target to enemy

**Comment by ZaneDubya** [comment]
Ok - I was wondering if they were somehow tied into a server feature that I couldn't find. I like the idea, but I think it does need a corresponding server feature that does not yet exist. So I'm going to take them out.

Should have this in tomorrow!

**Pull request merged**
