### PR TITLE
Loading and saving values from Settings.ini file 

### PR DESCRIPTION
**Pull request by PatrikSamuelTauchim**
Loading and saving values from Settings.ini file. Code from from:
http://www.codeproject.com/Articles/20053/A-Complete-Win-INI-File-Utility-Class
under Code Project Open License
http://www.codeproject.com/info/cpol10.aspx

Values, that can be used to overide defaults:
UDData = location of UO instalation
AlwaysRun = self explanatory feature from CC
LastAccount = Account field at login screen is prefiled with last used
account
ServerIP = self explanatory
ServerPort = self explanatory

### CODE REVIEW

**Comment by PatrikSamuelTauchim** [comment]
Do we want this? :-)

**Comment by ZaneDubya** [comment]
I think this is a great idea! I am out of town until monday and won't be able to thoroughly test it until then.

Based on a quick perusal of the code, here are my questions:
- If you didn't write it, where is the .ini file reading code from? What is the license?
- Rather than loading an iniFile object every time we want to reference the Settings, could we instead create a class that would load all the settings in at runtime, save them at exit, allow access to the variables from that class? I would use the various singletons in the UltimaVars namespace as templates for this; perhaps a static Settings class?

**Comment by PatrikSamuelTauchim** [comment]
- As stated in first post: Code from:
  http://www.codeproject.com/Articles/20053/A-Complete-Win-INI-File-Utility-Class
  under Code Project Open License
  http://www.codeproject.com/info/cpol10.aspx
- I will look at it, makes more sence :-)

**Comment by Vodacek** [comment]
why not use original configuration files like uo.cfg?
they are easy to parse (read file line by line and then simply read key and value parts separated by '=')
with that we won't need to use these dllimports

**Comment by ZaneDubya** [comment]
Thank you for including that information up top - sorry for missing it!

As to why use ini files - one could make an argument as to using ini files, xml files, or a simpler format like uo.cfg uses. Whatever way is implemented, we'll need file writing and parsing code. As long as the settings are exposed to the program in a well thought out way (I imagine placing them in a single Settings class, with the ability to Load() and Save() those settings would be one way of doing it), it doesn't matter as to how the data is written to the hard drive.

**Comment by PatrikSamuelTauchim** [comment]
@Vodacek I dont think is good idea to modify original configuration file that is shared with different application (classic client).

@ZaneDubya Yep, at first, I decided to used ini file because is easier to modify by hand, compared to XML. And also because I found this working code. :-)

I think we really need to have basic configuration functionality, even at this stage. Personally I feel tired of need to modify the same code again and again, to change UO files location, server ip, and so on. And we can always replace this with something better in future.

So, I am working on suggested changes.

**Comment by ZaneDubya** [comment]
@Eskymak I'm going to close this PR for now - please reopen it when your code is ready.

**Pull request closed without merging**
