### PR TITLE
Option: Macro Manager Added

### PR DESCRIPTION
**Pull request by msx752**
visual design finished
add,delete,previous,next button events are working
dropdown fill method is working
keypress is working (first DoubleClick for activate)
read/write macro from file is working
default some macros added
in game keyboard handle included
[paperdol title added (BUG:after first login paperdoll text empty)]

i need  "macrosettings.UseMacro()" to development for more macro combination

### CODE REVIEW

**Comment by msx752** [comment]
switch case which UseMacro's method is index numbers wrong. example: "targert self" i writed case 17: but case 23: correct and case 22: Last Targert correct....

i dont know how that code's performance

**Comment by ZaneDubya** [comment]
@MSAlih1 I'll make sure to take a look at that.

**Comment by ZaneDubya** [comment]
@MSAlih1 Please separate the party features into its own PR. Thank you!

**Comment by msx752** [comment]
okey.  i have some sync problem ops sorry

**Comment by ZaneDubya** [comment]
np! thanks! I just like to work on one thing at a time, particularly when the 'one thing' is quite large, as with your macro menu.

**Comment by msx752** [comment]
okey
develop branch crowded so i trying to fix it 
 i moved to here macro features  https://github.com/MSAlih1/UltimaXNA/tree/new-macros .
i seperate the party features to here https://github.com/MSAlih1/UltimaXNA/tree/new-PartySystem

**Comment by ZaneDubya** [comment]
I'm almost done reading this code - it's really good! Two thoughts:
1. I'm going to revise the code so the indexes you have for each of the macro definitions are named constants.
2. I realize that a lot of the macros don't work yet, because the xna client doesn't have the functionality necessary to give them action. What I'm going to do is comment out all the macros that don't have functionality yet - and then we can add them back as the client gains the functionality. I'll also open an issue with a checklist for the missing functions.

Hopefully I'll have this branch merged this weekend. Thanks again!

**Comment by msx752** [comment]
np,! it's really good idea. i am waiting for the running macro system :)

**Comment by msx752** [comment]
Please Add two commits into the branch:MSAlih1-macros. Thank you!

**Comment by ZaneDubya** [comment]
@MSAlih1 I've integrated the macro menu - looking good! I don't have a macro system running yet - this might take another week or two to get working. But this is a great step in the right direction!

If you're interested, the macro running stub that I have in the game is in Ultima.Input.MacroEngine.

**Comment by msx752** [comment]
final version of macro system is really good. i am looking at codes awesome. it was orginally and i think it is better than classic client's macro system. Thank You.!!

**Comment by ZaneDubya** [comment]
Excellent - thank you!

**Pull request merged**
